image: docker:18.09.9

services:
  - docker:18.09.9-dind

stages:
  - build
  - package
  - deploy

variables:
  APP_VERSION: v1.4
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
    - back/target
    - .npm

build:back:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
    - cd back
    - mvn package $MAVEN_CLI_OPTS -Pprod -DskipTests
  artifacts:
    paths:
      - back/target

build:front:
  image: node:12-alpine
  stage: build
  script:
    - cd front
    - npm ci
    - npm run build:prod
  artifacts:
    paths:
      - front/build

package:back:
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY/vely/iseplive-back:$APP_VERSION -t $CI_REGISTRY/vely/iseplive-back:latest -f back/Dockerfile .
    - docker push $CI_REGISTRY/vely/iseplive-back:$APP_VERSION
    - docker push $CI_REGISTRY/vely/iseplive-back:latest
  dependencies:
    - build:back

package:front:
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY/vely/iseplive-front:$APP_VERSION -t $CI_REGISTRY/vely/iseplive-front:latest -f front/Dockerfile .
    - docker push $CI_REGISTRY/vely/iseplive-front:$APP_VERSION
    - docker push $CI_REGISTRY/vely/iseplive-front:latest
  dependencies:
    - build:front
